### ISSUE TITLE
Allow multiple placeholders on one line

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/exoskeleton.vim#2]
I haven't tried this but I'm quite certain it would only evaluate the first one.

**Comment by andreyorst** [comment]
it probably won't evaluate anything. For this example: `The year is {{strftime("%Y")}} The year is {{strftime("%Y")}}`, as I see here: https://github.com/joereynolds/exoskeleton.vim/blob/5cf61d93a9e57616bce8b14d2428f7fa78ccd8ff/autoload/exoskeleton.vim#L25
you're executing everything (`.*`) between delimiters `{{` and `}}` which mean that star will be equal to `strftime("%Y")}} The year is {{strftime("%Y")`. You need non-greedy `.{-}` instead of `.*`. 
To evaluate several placeholders in one line you need to count them and run evaluation script several times. There is no easy way of calculating regex matches in file except of using `redir`

**Comment by andreyorst** [comment]
You need [something like this](https://github.com/andreyorst/SimpleSnippets.vim/blob/050899312f25c8897436cdc01d6fbddea9c2ec50/autoload/SimpleSnippets.vim#L613-L624) to count all occuriences of your placeholders in current line:
```vim
function! SimpleSnippets#countPlaceholders(pattern)
	redir => l:cnt
	silent! exe '%s/' . a:pattern . '//gn'
	redir END
	call histdel("/", -1)
	if match(l:cnt, 'not found') >= 0
		return 0
	endif
	let l:count = strpart(l:cnt, 0, stridx(l:cnt, " "))
	let l:count = substitute(l:count, '\v%^\_s+|\_s+%$', '', 'g')
	return l:count
endfunction
```
except for `exec` part you need to search only in current line, not whole file.

**Comment by joereynolds** [comment]
Hey @andreyorst,

Thanks for the suggestions, I ended up going for the non greedy regex `.\{-}`

https://github.com/joereynolds/exoskeleton.vim/commit/662c76d8561b3fbd17ba7ba293d8e0ea4c4bc3ac
